### ISSUE TITLE
Pytorch Issue Windows

### ISSUE THREAD

**Issue by FabyOfficial** [graknlabs/kglib#48]
I try to install pytorch and after days of trying I`m here with a big, big problem. I read a lot of articles of "how to install pytorch" I try to install with pip install but don`t work for me and after I install it with Anaconda, but in anaconda is pytorch install, when I type: conda list, he is there like this form: pytorch                   1.0.1           py3.7_cuda100_cudnn7_1    pytorch, I have python 3.7, when I run a code with import torch this show me a message like this: 

![problem](https://user-images.githubusercontent.com/46923580/52486017-d2b15e80-2bc2-11e9-96d3-e2f96bda4154.PNG)

And when i try to import torch in python 3.7:

![fdzzddz](https://user-images.githubusercontent.com/46923580/52486084-eeb50000-2bc2-11e9-9bd1-6a95b8b331e3.PNG)

Pip install error:

![dsfdasad](https://user-images.githubusercontent.com/46923580/52486140-0a200b00-2bc3-11e9-8598-5505965aa7c2.PNG)

How to pass this errors? Please Help, thx.

**Comment by jmsfltchr** [comment]
Hi,
PyTorch isn't needed to use kglib! All of the dependencies for kglib will be installed automatically when you `pip install grakn-kglib`, using Python 3.6. For installation instructions please follow the Quickstart in the READMEs.

If you encounter issues installing kglib in this way then please open a new issue. Since PyTorch isn't required for kglib I will close this issue.

**Comment by FabyOfficial** [comment]
Don`t work.

![numergeee](https://user-images.githubusercontent.com/46923580/52492903-e369d080-2bd2-11e9-82f1-dd1383102aa0.PNG)
